### ISSUE TITLE
PPM output

### ISSUE THREAD

**Issue by axljackass** [ZZ-Cat/CRSFforArduino#24]
Any support for PPM output and using Bluepill board?

**Comment by ZZ-Cat** [comment]
> Any support for PPM output and using Bluepill board?
> 
> 

CPPM is an outdated way of managing RC channels, & it is outside the scope of this project. I will not include it because of those two reasons.

I don't have any plans to add STM32 support yet. This is simply because I don't own any STM32 development boards (such as the Blue Pill). If I _did_ add STM32 compatibility, I would start with [these](https://www.adafruit.com/product/4382) [two](https://www.adafruit.com/product/4877) boards, because they are both easily accessible to me & because of things such as [this](https://hackaday.com/2021/01/20/blue-pill-vs-black-pill-transitioning-from-stm32f103-to-stm32f411/).

Right now, I need to focus on getting full CRSF compatibility (including telemetry) finished before I consider anything else.
