### ISSUE TITLE
please  support stm32 chip   in  arduino  fremework  and  vscode  pio 

### ISSUE THREAD

**Issue by zouzhe1** [ZZ-Cat/CRSFforArduino#58]
### Is there already an issue for this?

- [X] I have searched the issues and there is no existing issue for this feature request.

### Is your feature request related to a problem?

please  support stm32 chip   in  arduino  fremework  and  vscode  pio 

### Describe the solution you'd like

please  support stm32 chip   in  arduino  fremework  and  vscode  pio 

### Describe alternatives you've considered

please  support stm32 chip   in  arduino  fremework  and  vscode  pio

**Comment by ZZ-Cat** [comment]
Oooooooohhhh, STM32 chipsets are a rabbit hole and a half to which I am _not_ as familiar with, compared to the 10+ years of knowledge I have on Microchip's chipsets. STM32 chipsets are largely uncharted territory for me, so there is a learning curve here (to which, I would _love_ to take on).

Here is where I would start:

- STM32F103
- STM32F405
- STM32F722

I would like to add in STM32H745 support as well. However, the board support package for this chipset is not currently available to the Arduino IDE.

I have cherry-picked these four chipsets, because these are the same chipsets used in most drone flight controllers today, and are available as development boards as well.

This will be an interesting feature to have, as the more hardware agnostic CRSF for Arduino is, the better it will be.
